#!/bin/bash -e

if [[ $# -ne 1 ]]; then
	echo "Usage: $0 <app>" >&2
	exit 1
fi

app=$1
ver=0.1

docker build -t rchain/rdoctor-$app:$ver -f Dockerfile.$app .
docker tag rchain/rdoctor-$app:{$ver,latest}
