FROM rchain/rdoctor-build as build
COPY rest-api/requirements.txt .
RUN :\
  && python -mvenv venv \
  && source venv/bin/activate \
  && pip install -r requirements.txt \
  ;

FROM python:alpine
RUN adduser -S -h /home/alice alice
WORKDIR /home/alice
USER alice
COPY --from=build --chown=alice:0 /home/alice/venv venv
COPY rest-api/* ./
ENV BIND_PORT=8000
CMD source venv/bin/activate && exec hypercorn -b:$BIND_PORT server:app
